server:
  port: 6688
mysql:
  host: localhost
  port: 3306
  username: root
  password: Zjc123456!
  database: B2CShop
redis:
  host: localhost
  port: 6379
  db : 0

#其它的配置文件
resizeImageSize : 200,400
ossStatus : false
ossDomain : "http://oss-cn-shanghai.aliyuncs.com"
redisTime : 3600
enableRedis : true

secureCookie : "least123"
copyrequestbody : true
domain : ""